### ISSUE TITLE
Bluetooth messages send

### ISSUE THREAD

**Issue by baritonomarchetto** [simonnorberg/dmach#3]
Hi Simmon,
great piece of code you wrote! This is my favourite drum sequencer for android, fullstop.
This is not a issue really, but a feature request: would it be possible to add a feature such that drumach sends bytes at every step via bluetooth so that an external drum machine can be triggered?
I recently realized a bluetooth terminal + arduino system (an instructable will follow) but it lacks the great interface your drumach has.
Waiting for your answer, thank you!

**Comment by simonnorberg** [comment]
Thanks!

I have no time to add trigger support via Bluetooth and I'm not sure you would be able to keep an external device in sync. I think the only way it could work is if [pd-for-android](https://github.com/libpd/pd-for-android) has Bluetooth MIDI support.
