### ISSUE TITLE
Audio Rendering or Recording?

### ISSUE THREAD

**Issue by Paree24** [simonnorberg/dmach#4]
Hello, i love this app and id love to be able to use it for my tracks, but there is no facility to export wav or record wav. Is it possible to add it?

**Comment by forbidden303** [comment]
This would be a convenient functionality, however having the ability to save presets already, you could just load your user presets and record to your D.A.W .

**Comment by Paree24** [comment]
That would be possible if your main workflow involves recording gear. Also if your DAW is an android DAW you can't do that.

**Comment by simonnorberg** [comment]
There is no plan to add audio export right now. Maybe in the future.
